// Generated by sync-abis. Do not edit.
export const intervalPredicateAbi = [
  {
    "type": "function",
    "name": "isEligible",
    "inputs": [
      {
        "name": "subject",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "checkParam",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  }
] as const;
