/**
 * Copy selected contract ABIs from Foundry's `contracts/out` into
 * `packages/shared/src/abis/<Name>.ts` as `as const` exports, and regenerate
 * the barrel `abis/index.ts`. Run after `forge build`.
 *
 * Usage: pnpm --filter @reservoir/shared sync-abis
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "..", "..", "contracts", "out");
const ABIS_DIR = join(__dirname, "..", "src", "abis");

// Contracts whose ABIs the TS packages consume.
const CONTRACTS = [
  "Coordinator",
  "IEligibilityPredicate",
  "ICoordinator",
  "BaseExecutor",
  "AaveLiquidationExecutor",
  "DexArbExecutor",
  "HarvestExecutor",
  "AaveHealthPredicate",
  "PriceDivergencePredicate",
  "IntervalPredicate",
  "EnforcedMockPool",
  "MockOracle",
  "MockVault",
];

function abiExportName(name: string): string {
  return `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
}

function main() {
  if (!existsSync(OUT_DIR)) {
    throw new Error(`contracts/out not found at ${OUT_DIR}. Run \`forge build --root contracts\` first.`);
  }
  mkdirSync(ABIS_DIR, { recursive: true });

  const written: string[] = [];
  for (const name of CONTRACTS) {
    const artifactPath = join(OUT_DIR, `${name}.sol`, `${name}.json`);
    if (!existsSync(artifactPath)) {
      console.warn(`  skip ${name} (no artifact at ${artifactPath})`);
      continue;
    }
    const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown[] };
    const exportName = abiExportName(name);
    const body =
      `// Generated by sync-abis. Do not edit.\n` +
      `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
    writeFileSync(join(ABIS_DIR, `${name}.ts`), body);
    written.push(name);
    console.log(`  ✓ ${name} → abis/${name}.ts`);
  }

  const barrel =
    `// Generated by sync-abis. Do not edit by hand.\n` +
    (written.length === 0
      ? `export {};\n`
      : written.map((n) => `export { ${abiExportName(n)} } from "./${n}.js";`).join("\n") + "\n");
  writeFileSync(join(ABIS_DIR, "index.ts"), barrel);

  console.log(`\nSynced ${written.length}/${CONTRACTS.length} ABIs.`);
}

main();
